name: m_hike
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^7.8.3
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  flutter_animate: ^4.2.0+1
  freezed_annotation: ^2.4.1
  isar: ^3.1.0+1
  intl: ^0.18.1
  injectable: ^2.3.0
  gap: ^3.0.1

dev_dependencies:
  freezed: any
  build_runner: ^2.4.6
  isar_generator: 3.1.0+1
  auto_route_generator: ^7.3.1
  injectable_generator: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
